[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "info"

[build]
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]